# This is a basic workflow to help you get started with Actions

name: Screenshot

on:
  schedule:
    - cron:  '*/1 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        width: [1920, 1024]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Take screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: "http://www.centrometeolombardo.com/moduli/stazioni.php?lema"
        destination: screenshot.png

    - name: Download screenshot from last step
      uses: actions/download-artifact@v1
      with:
        name: screenshot

    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Updated weather screenshots
        branch: ${{ github.head_ref }}
