# This is a basic workflow to help you get started with Actions

name: Screenshot

on:
  schedule:
    - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  take:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Take screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: "http://www.centrometeolombardo.com/moduli/stazioni.php?lema"
        destination: screenshot.png
        full-page: true
        width: 1200
  persist:
    runs-on: ubuntu-latest
    needs: take
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Download screenshot from last step
      uses: actions/download-artifact@v2
      with:
        name: screenshot
        path: weather-screenshots/
    - name: Persist 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated weather screenshots
